INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX, FUNCTIONIMAGE) VALUES ('zh-CN', 1, '企业数据维护', 'FCompany', 1, 1, 'CompanyData');
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX, FUNCTIONIMAGE) VALUES ('zh-CN', 2, '日历设定', 'FCalendar', 1, 2, 'Calendar');
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX, FUNCTIONIMAGE) VALUES ('en-US', 1, 'Company Data', 'FCompany', 1, 1, 'CompanyData');
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX, FUNCTIONIMAGE) VALUES ('en-US', 2, 'Calandar', 'FCalendar', 1, 2, 'Calendar');
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX, FUNCTIONIMAGE) VALUES ('zh-CN', 3, '报价单输入', 'FQuotationEntry', 2, 1, 'QuotationEntry');
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX, FUNCTIONIMAGE) VALUES ('zh-CN', 4, '报价单检索', 'FQuotationSearch', 2, 2, 'QuotationSearch');
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX, FUNCTIONIMAGE) VALUES ('en-US', 3, 'Quote Input', 'FQuotationEntry', 2, 1, 'QuotationEntry');
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX, FUNCTIONIMAGE) VALUES ('en-US', 4, 'Quote Search', 'FQuotationSearch', 2, 2, 'QuotationSearch');
