INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX) VALUES ('zh-CN', 1, '企业数据维护', 'FrmCompany', 1, 1);
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX) VALUES ('zh-CN', 2, '日历设定', 'FrmCalandar', 1, 2);
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX) VALUES ('en-US', 1, 'Company Data', 'FrmCompany', 1, 1);
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX) VALUES ('en-US', 2, 'Calandar', 'FrmCalandar', 1, 2);
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX) VALUES ('zh-CN', 3, '报价单输入', 'FrmQuoteInput', 2, 1);
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX) VALUES ('zh-CN', 4, '报价单检索', 'FrmQuoteSearch', 2, 2);
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX) VALUES ('en-US', 3, 'Quote Input', 'FrmQuoteInput', 2, 1);
INSERT INTO PDM.M_FUNCTION(LANGID, FUNCTIONID, FUNCTIONNAME, FUNCTIONPATH, CATALOGID, FUNCTIONINDEX) VALUES ('en-US', 4, 'Quote Search', 'FrmQuoteSearch', 2, 2);
