--------------------------------------------------------
--  文件已？建 - 星期四-九月-08-2011   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table M_ROLE
--------------------------------------------------------

  CREATE TABLE "PDM"."M_ROLE" 
   (	"ROLEID" NUMBER(3,0), 
	"ROLENAME" VARCHAR2(20 BYTE), 
	"CREATEDATETIME" TIMESTAMP (6), 
	"CREATEUSERID" NVARCHAR2(20), 
	"UPDATEDATETIME" TIMESTAMP (6), 
	"UPDATEUSERID" VARCHAR2(20 BYTE), 
	"DELETEFLAG" NVARCHAR2(1)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index M_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDM"."M_ROLE_PK" ON "PDM"."M_ROLE" ("ROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table M_ROLE
--------------------------------------------------------

  ALTER TABLE "PDM"."M_ROLE" ADD CONSTRAINT "M_ROLE_PK" PRIMARY KEY ("ROLEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PDM"."M_ROLE" MODIFY ("ROLEID" NOT NULL ENABLE);
