--------------------------------------------------------
--  文件已？建 - 星期五-九月-09-2011   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table M_ROLE_USER
--------------------------------------------------------

  CREATE TABLE "PDM"."M_ROLE_USER" 
   (	"ROLEID" NUMBER(3,0), 
	"USERID" VARCHAR2(20 BYTE), 
	"CREATEDATETIME" TIMESTAMP (6), 
	"CREATEUSERID" VARCHAR2(20 BYTE), 
	"UPDATEDATETIME" TIMESTAMP (6), 
	"UPDATEUSERID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index M_ROLE_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDM"."M_ROLE_USER_PK" ON "PDM"."M_ROLE_USER" ("ROLEID", "USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table M_ROLE_USER
--------------------------------------------------------

  ALTER TABLE "PDM"."M_ROLE_USER" ADD CONSTRAINT "M_ROLE_USER_PK" PRIMARY KEY ("ROLEID", "USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PDM"."M_ROLE_USER" MODIFY ("ROLEID" NOT NULL ENABLE);
 
  ALTER TABLE "PDM"."M_ROLE_USER" MODIFY ("USERID" NOT NULL ENABLE);
