CREATE TABLE M_ROLE
(
    ROLEID                         NUMBER(3,0) NOT NULL,
    ROLENAME                       VARCHAR2(20),
    CREATEDATETIME                 TIMESTAMP(6),
    CREATEUSERID                   NVARCHAR2(20),
    UPDATEDATETIME                 TIMESTAMP(6),
    UPDATEUSERID                   VARCHAR2(20),
    DELETEFLAG                     NVARCHAR2(1),
    CONSTRAINT M_ROLE_PK PRIMARY KEY (ROLEID) USING INDEX
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        TABLESPACE USERS
        STORAGE(INITIAL 64K MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
        LOGGING
)
PCTFREE 10
MAXTRANS 255
TABLESPACE USERS
STORAGE(INITIAL 64K MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
NOCACHE
LOGGING
/
INSERT INTO M_ROLE values(1,'admin',null,null,null,null,null)
/
