INSERT INTO PDM.M_FUNCTIONCATALOG(LANGID, CATALOGID, CATALOGNAME, CATALOGIMAGE) VALUES ('zh-CN', 2, '报价/订单', 'Quote');
INSERT INTO PDM.M_FUNCTIONCATALOG(LANGID, CATALOGID, CATALOGNAME, CATALOGIMAGE) VALUES ('zh-CN', 1, '基础数据', 'MasterData');
INSERT INTO PDM.M_FUNCTIONCATALOG(LANGID, CATALOGID, CATALOGNAME, CATALOGIMAGE) VALUES ('en-US', 1, 'Master Data Maintenance', 'MasterData');
INSERT INTO PDM.M_FUNCTIONCATALOG(LANGID, CATALOGID, CATALOGNAME, CATALOGIMAGE) VALUES ('en-US', 2, 'Quotaion&Order', 'Quote');
