using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using Castle.ActiveRecord;
using Castle.ActiveRecord.Queries;


#region 'M_FUNCTION' Schema
/*
 * 'MFunction' class maps to 'M_FUNCTION' table.
 * 	 LANGID                  | Type:NVARCHAR2 | Len:10    | Nullable:F | PK:T | FK:F
 * 	 FUNCTIONID              | Type:NUMBER    | Len:0     | Nullable:F | PK:T | FK:F
 * 	 FUNCTIONNAME            | Type:NVARCHAR2 | Len:100   | Nullable:T | PK:F | FK:F
 * 	 FUNCTIONPATH            | Type:NVARCHAR2 | Len:100   | Nullable:T | PK:F | FK:F
 * 	 CATALOGID               | Type:NUMBER    | Len:0     | Nullable:F | PK:F | FK:F
 */
#endregion
/// <summary>
///	Generated by MyGeneration using the ActiveRecord Object Mapper - 1.0.2
///	
/// 关于成员属性的取名，为了多语言里，避免grid的字段名和card部的字段名冲突
/// 强烈建议grid的属性定义时加上grid_前缀
/// 
///	Created on 2011/8/24 20:15:02
/// </summary>
namespace Com.GainWinSoft.ERP.Entity
{

    public class CFunctionPagerNoAR 
    {

		#region Private Members

        private string grid_langid;
        public string Grid_langid
        {
            get { return grid_langid; }
            set { grid_langid = value; }
        }
        private int grid_functionid;

        public int Grid_functionid
        {
            get { return grid_functionid; }
            set { grid_functionid = value; }
        }

        private string grid_functionname;
        public string Grid_functionname
        {
            get { return grid_functionname; }
            set { grid_functionname = value; }
        }
        private string grid_functionpath;

        public string Grid_functionpath
        {
            get { return grid_functionpath; }
            set { grid_functionpath = value; }
        }
        private int grid_catalogid;

        public int Grid_catalogid
        {
            get { return grid_catalogid; }
            set { grid_catalogid = value; }
        }
        private int grid_functionindex;

        public int Grid_functionindex
        {
            get { return grid_functionindex; }
            set { grid_functionindex = value; }
        }
        private string grid_functionimage;

        public string Grid_functionimage
        {
            get { return grid_functionimage; }
            set { grid_functionimage = value; }
        }

  		
		#endregion

	}
}
