using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using Castle.ActiveRecord;
using Castle.ActiveRecord.Queries;


#region 'M_FUNCTION' Schema
/*
 * 'MFunction' class maps to 'M_FUNCTION' table.
 * 	 LANGID                  | Type:NVARCHAR2 | Len:10    | Nullable:F | PK:T | FK:F
 * 	 FUNCTIONID              | Type:NUMBER    | Len:0     | Nullable:F | PK:T | FK:F
 * 	 FUNCTIONNAME            | Type:NVARCHAR2 | Len:100   | Nullable:T | PK:F | FK:F
 * 	 FUNCTIONPATH            | Type:NVARCHAR2 | Len:100   | Nullable:T | PK:F | FK:F
 * 	 CATALOGID               | Type:NUMBER    | Len:0     | Nullable:F | PK:F | FK:F
 */
#endregion
/// <summary>
///	Generated by MyGeneration using the ActiveRecord Object Mapper - 1.0.2
///	
/// 
///	Created on 2011/8/24 20:15:02
/// </summary>
namespace Com.GainWinSoft.ERP.Entity
{
    [Serializable]
    public class CTPmMsNoAR
    {
        #region Private Members

        private string iFacCd;
        private string iItemCd;
        private string iDispItemCd;
        private string iItemDesc;
        private string iItemRev;
        private string iDispItemRev;
        private string iModel;
        private string iDrwNo;
        private string iSpec;
        private string iSeiban;
        private string iItemType;
        private string iItemType1;
        //用作客户代码
        private string iDlCd;  //iItemType2
        //用作课税区分
        private string iItemType3;
        private string iSalesPersonCd;
        private string iCtrlCls;
        private string iItemCls;
        private string iSoAlcCls;
        private string iPsCls;
        private string iLotMethod;
        private decimal iFprPeriod;
        private decimal iLotQty;
        private string iLotCtrlCls;
        private string iStockCls;
        private string iDelSchCls;
        private string iOsAlcCls;
        private string iPlanDvdCls;
        private decimal iMinLotQty;
        private decimal iSafeStockQty;
        private string iUseDelCls;
        private string iStdUnitCd;
        private decimal iStartSeq;
        private decimal iEndSeq;
        private string iCnvUnitCd;
        private decimal iCnvRateBunsi;
        private decimal iCnvRateBunbo;
        private decimal iInvSoDate;
        private string iShipLocation;
        private decimal iNetWeight;
        private string iNetWeightUnit;
        private decimal iGrossWeight;
        private string iGrossWeightUnit;
        private decimal iM3;
        private decimal iLowLevel;
        private decimal iSumLt;
        private decimal iPlanQty;
        private string iMakerCd;
        private string iQryMtrl;
        private decimal iSize1;
        private decimal iSize2;
        private decimal iSize3;
        private decimal iGravity;
        private string iProdFacCd;
        private string iFgInCls;
        private decimal iProcSumLt;
        private string iHcdflg;
        private string iSpflg;
        private string iSpexc;
        private string iPmrkey;
        private decimal iPmrver;
        private string iSpname;
        private DateTime iSpdate;
        private string iStatus;
        private string iSephin;
        private string iRyuhin;
        private string iSakusei;
        private string iCtrlSection;
        private string iSalesSection;
        private string iPurchaseSection;
        private string iItemEntryCls;
        private string iSmtCls;
        private string iRohsCls;
        private string iReachCls;
        private string iChinaRohsCls;
        private decimal iBinEndDate;
        private string iMntCls;
        private string iSrlSeqCls;
        private decimal iPartChgPeriod;
        private string iPartChgPeriodUnitCd;
        private decimal iFixMntPeriod;
        private string iFixMntPeriodUnitCd;
        private decimal iGuarPeriod;
        private string iGuarPeriodUnitCd;
        private decimal iUsefulLife;
        private string iUsefulLifeUnitCls;
        private string iCapItemType;
        private string iInqItem;
        private decimal iObjectId;
        private DateTime iEntryDate;
        private DateTime iUpdDate;
        private string iUpdTimestamp;

        //pm_ms_add_rtcm 所有字段
        private string iHinsyosai1;
        private string iHinsyosai2;
        private string iHinsyosai3;
        private string iHinsyosai4;
        private string iHinsyosai5;
        private string iHkhinno1;
        private string iHkhinno2;
        private string iHkhinno3;
        private string iHinzks1;
        private string iHinzks2;
        private string iHinzks3;
        private string iZryobnr;
        private string iCsthskkbn;
        private string iCstkskbn;
        private string iKgsankbn;
        private string iSkrkejkbn;
        private string iTmhskkbn;
        private string iTmzryobnr;
        private decimal iTmcstmkno;
        private string iSzcrtkbn;
        private decimal iHdtkzchBnshi;
        private decimal iHdtkzchBnbo;
        private string iHdkmtnicd;
        private decimal iLotSesanryo;
        private decimal iDaySesanryo;
        private decimal iYieldRate;
        private string iFukukbn;
        private string iSgenkbn;
        private string iTenfuykbn;
        private string iDaikoteptn;
        private string iDhhigptn;
        private decimal iZktkzchBnshi1;
        private decimal iZktkzchBnbo1;
        private string iZktikzticd1;
        private decimal iZktkzchBnshi2;
        private decimal iZktkzchBnbo2;
        private string iZktikzticd2;
        private decimal iZktkzchBnshi3;
        private decimal iZktkzchBnbo3;
        private string iZktikzticd3;
        private decimal iZktkzchBnshi4;
        private decimal iZktkzchBnbo4;
        private string iZktikzticd4;
        private decimal iZktkzchBnshi5;
        private decimal iZktkzchBnbo5;
        private string iZktikzticd5;
        private decimal iHinksu01;
        private decimal iHinksu02;
        private decimal iHinksu03;
        private decimal iHinksu04;
        private decimal iHinksu05;
        private decimal iHinksu06;
        private decimal iHinksu07;
        private decimal iHinksu08;
        private decimal iHinksu09;
        private decimal iHinksu10;
        private string iHinbnr01;
        private string iHinbnr02;
        private string iHinbnr03;
        private string iHinbnr04;
        private string iHinbnr05;
        private string iHinbnr06;
        private string iHinbnr07;
        private string iHinbnr08;
        private string iHinbnr09;
        private string iHinbnr10;
        private string iJohhtkbn;
        private string iHftkbn1;
        private string iHftkbn2;
        private string iHftkbn3;
        private string iHftkbn4;
        private string iHftkbn5;
        private string iSytsukakbn;
        private string iTngmhfkbn;
        private string iTnhkshfkbn;

        //
        //所有区分的名称字段
        private string vItemclsdesc;
        private string vCtrlclsdesc;
        private string vLotctrlclsdesc;
        private string vUsedelclsdesc;
        private string vSoalcclsdesc;
        private string vPsclsdesc;
        private string vSmtclsdesc;
        private string vRohsclsdesc;
        private string vReachclsdesc;
        private string vChinarohsclsdesc;
        private string vOsalcclsdesc;
        private string vCsthskkbndesc;
        private string vCstkskbndesc;
        private string vKgsankbndesc;
        private string vSkrkejkbndesc;
        private string vTmhskkbndesc;
        private string vSzcrtkbndesc;
        private string vFukukbndesc;
        private string vSgenkbndesc;
        private string vTenfuykbndesc;
        private string vJohhtkbndesc;
        private string vHftkbndesc1;
        private string vHftkbndesc2;
        private string vHftkbndesc3;
        private string vHftkbndesc4;
        private string vHftkbndesc5;
        private string vItemtypedesc;
        private string vItemtype1desc;
        //客户名称
        private string vDlDesc;                    //vItemtype2desc;  
        //课税区分 区分代码=18
        private string vItemtype3desc;
        private string vMakerdesc;
        private string vZryobnrdesc;
        private string vTmzryobnrdesc;
        private string vHinbnr01desc;
        private string vHinbnr02desc;
        private string vHinbnr03desc;
        private string vHinbnr04desc;
        private string vHinbnr05desc;
        private string vHinbnr06desc;
        private string vHinbnr07desc;
        private string vHinbnr08desc;
        private string vHinbnr09desc;
        private string vHinbnr10desc;
        private string vHdkmtnicddesc;
        private string vZktikzticd1desc;
        private string vZktikzticd2desc;
        private string vZktikzticd3desc;
        private string vZktikzticd4desc;
        private string vZktikzticd5desc;
        private string vCtrlsectiondesc;
        private string vStocklocationdesc;
        private string vFacdesc;
        private string vPersondesc;
        private string iStdunitdesc;
        private string iCnvunitdesc;
        private string iNetweightunitdesc;
        private string iPartchgperiodunitdesc;
        private string iFixmntperiodunitdesc;
        private string iGuarperiodunitdesc;
        private string iMntclsdesc;
        private string iSrlseqclsdesc;
        private string iUsefullifeunitclsdesc;
        /*
         *
         * V_ITEM_CLS_DESC
         * V_CTRL_CLS_DESC
         * V_LOT_CTRL_CLS_DESC
         * V_USE_DEL_CLS_DESC
         * V_SO_ALC_CLS_DESC
         * V_PS_CLS_DESC
         * V_SMT_CLS_DESC
         * V_ROHS_CLS_DESC
         * V_REACH_CLS_DESC
         * V_CHINA_ROHS_CLS_DESC
         * V_OS_ALC_CLS_DESC
         * V_CSTHSKKBN_DESC
         * V_CSTKSKBN_DESC
         * V_KGSANKBN_DESC
         * V_SKRKEJKBN_DESC
         * V_TMHSKKBN_DESC
         * V_SZCRTKBN_DESC
         * V_FUKUKBN_DESC
         * V_SGENKBN_DESC
         * V_TENFUYKBN_DESC
         * V_JOHHTKBN_DESC
         * V_HFTKBN_DESC1
         * V_HFTKBN_DESC2
         * V_HFTKBN_DESC3
         * V_HFTKBN_DESC4
         * V_HFTKBN_DESC5
         * V_ITEM_TYPE_DESC
         * V_ITEMTYPE1_DESC
         * V_ITEMTYPE2_DESC
         * V_ITEMTYPE3_DESC
         * V_MAKER_DESC
         * V_ZRYOBNR_DESC
         * V_TMZRYOBNR_DESC
         * V_HINBNR01_DESC
         * V_HINBNR02_DESC
         * V_HINBNR03_DESC
         * V_HINBNR04_DESC
         * V_HINBNR05_DESC
         * V_HINBNR06_DESC
         * V_HINBNR07_DESC
         * V_HINBNR08_DESC
         * V_HINBNR09_DESC
         * V_HINBNR10_DESC
         * V_HDKMTNICD_DESC
         * V_ZKTIKZTICD1_DESC
         * V_ZKTIKZTICD2_DESC
         * V_ZKTIKZTICD3_DESC
         * V_ZKTIKZTICD4_DESC
         * V_ZKTIKZTICD5_DESC
         * V_CTRL_SECTION_DESC
         * V_STOCK_LOCATION_DESC
         * V_FAC_DESC
         * V_PERSON_DESC
         * I_STD_UNIT_DESC
         * I_CNV_UNIT_DESC
         * I_NET_WEIGHT_UNIT_DESC
         * I_PART_CHG_PERIOD_UNIT_DESC
         * I_FIX_MNT_PERIOD_UNIT_DESC
         * I_GUAR_PERIOD_UNIT_DESC
         * I_MNT_CLS_DESC
         * I_SRL_SEQ_CLS_DESC
         * I_USEFUL_LIFE_UNIT_CLS_DESC
         * 
         * 
        
        

        */

        #endregion


        public string IFacCd
        {
            get { return iFacCd; }
            set { iFacCd = value; }
        }

        public string IItemCd
        {
            get { return iItemCd; }
            set { iItemCd = value; }
        }



        public string IDispItemCd
        {
            get { return iDispItemCd; }
            set { iDispItemCd = value; }
        }

        public string IItemDesc
        {
            get { return iItemDesc; }
            set { iItemDesc = value; }
        }

        public string IItemRev
        {
            get { return iItemRev; }
            set { iItemRev = value; }
        }

        public string IDispItemRev
        {
            get { return iDispItemRev; }
            set { iDispItemRev = value; }
        }

        public string IModel
        {
            get { return iModel; }
            set { iModel = value; }
        }

        public string IDrwNo
        {
            get { return iDrwNo; }
            set { iDrwNo = value; }
        }

        public string ISpec
        {
            get { return iSpec; }
            set { iSpec = value; }
        }

        public string ISeiban
        {
            get { return iSeiban; }
            set { iSeiban = value; }
        }

        public string IItemType
        {
            get { return iItemType; }
            set { iItemType = value; }
        }

        public string IItemType1
        {
            get { return iItemType1; }
            set { iItemType1 = value; }
        }


        public string IItemType3
        {
            get { return iItemType3; }
            set { iItemType3 = value; }
        }

        public string ISalesPersonCd
        {
            get { return iSalesPersonCd; }
            set { iSalesPersonCd = value; }
        }

        public string ICtrlCls
        {
            get { return iCtrlCls; }
            set { iCtrlCls = value; }
        }

        public string IItemCls
        {
            get { return iItemCls; }
            set { iItemCls = value; }
        }

        public string ISoAlcCls
        {
            get { return iSoAlcCls; }
            set { iSoAlcCls = value; }
        }

        public string IPsCls
        {
            get { return iPsCls; }
            set { iPsCls = value; }
        }

        public string ILotMethod
        {
            get { return iLotMethod; }
            set { iLotMethod = value; }
        }

        public decimal IFprPeriod
        {
            get { return iFprPeriod; }
            set { iFprPeriod = value; }
        }

        public decimal ILotQty
        {
            get { return iLotQty; }
            set { iLotQty = value; }
        }

        public string ILotCtrlCls
        {
            get { return iLotCtrlCls; }
            set { iLotCtrlCls = value; }
        }

        public string IStockCls
        {
            get { return iStockCls; }
            set { iStockCls = value; }
        }

        public string IDelSchCls
        {
            get { return iDelSchCls; }
            set { iDelSchCls = value; }
        }

        public string IOsAlcCls
        {
            get { return iOsAlcCls; }
            set { iOsAlcCls = value; }
        }

        public string IPlanDvdCls
        {
            get { return iPlanDvdCls; }
            set { iPlanDvdCls = value; }
        }

        public decimal IMinLotQty
        {
            get { return iMinLotQty; }
            set { iMinLotQty = value; }
        }

        public decimal ISafeStockQty
        {
            get { return iSafeStockQty; }
            set { iSafeStockQty = value; }
        }

        public string IUseDelCls
        {
            get { return iUseDelCls; }
            set { iUseDelCls = value; }
        }

        public string IStdUnitCd
        {
            get { return iStdUnitCd; }
            set { iStdUnitCd = value; }
        }

        public decimal IStartSeq
        {
            get { return iStartSeq; }
            set { iStartSeq = value; }
        }

        public decimal IEndSeq
        {
            get { return iEndSeq; }
            set { iEndSeq = value; }
        }

        public string ICnvUnitCd
        {
            get { return iCnvUnitCd; }
            set { iCnvUnitCd = value; }
        }

        public decimal ICnvRateBunsi
        {
            get { return iCnvRateBunsi; }
            set { iCnvRateBunsi = value; }
        }

        public decimal ICnvRateBunbo
        {
            get { return iCnvRateBunbo; }
            set { iCnvRateBunbo = value; }
        }

        public decimal IInvSoDate
        {
            get { return iInvSoDate; }
            set { iInvSoDate = value; }
        }

        public string IShipLocation
        {
            get { return iShipLocation; }
            set { iShipLocation = value; }
        }

        public decimal INetWeight
        {
            get { return iNetWeight; }
            set { iNetWeight = value; }
        }

        public string INetWeightUnit
        {
            get { return iNetWeightUnit; }
            set { iNetWeightUnit = value; }
        }

        public decimal IGrossWeight
        {
            get { return iGrossWeight; }
            set { iGrossWeight = value; }
        }

        public string IGrossWeightUnit
        {
            get { return iGrossWeightUnit; }
            set { iGrossWeightUnit = value; }
        }

        public decimal IM3
        {
            get { return iM3; }
            set { iM3 = value; }
        }

        public decimal ILowLevel
        {
            get { return iLowLevel; }
            set { iLowLevel = value; }
        }

        public decimal ISumLt
        {
            get { return iSumLt; }
            set { iSumLt = value; }
        }

        public decimal IPlanQty
        {
            get { return iPlanQty; }
            set { iPlanQty = value; }
        }

        public string IMakerCd
        {
            get { return iMakerCd; }
            set { iMakerCd = value; }
        }

        public string IQryMtrl
        {
            get { return iQryMtrl; }
            set { iQryMtrl = value; }
        }

        public decimal ISize1
        {
            get { return iSize1; }
            set { iSize1 = value; }
        }

        public decimal ISize2
        {
            get { return iSize2; }
            set { iSize2 = value; }
        }

        public decimal ISize3
        {
            get { return iSize3; }
            set { iSize3 = value; }
        }

        public decimal IGravity
        {
            get { return iGravity; }
            set { iGravity = value; }
        }

        public string IProdFacCd
        {
            get { return iProdFacCd; }
            set { iProdFacCd = value; }
        }

        public string IFgInCls
        {
            get { return iFgInCls; }
            set { iFgInCls = value; }
        }

        public decimal IProcSumLt
        {
            get { return iProcSumLt; }
            set { iProcSumLt = value; }
        }

        public string IHcdflg
        {
            get { return iHcdflg; }
            set { iHcdflg = value; }
        }

        public string ISpflg
        {
            get { return iSpflg; }
            set { iSpflg = value; }
        }

        public string ISpexc
        {
            get { return iSpexc; }
            set { iSpexc = value; }
        }

        public string IPmrkey
        {
            get { return iPmrkey; }
            set { iPmrkey = value; }
        }

        public decimal IPmrver
        {
            get { return iPmrver; }
            set { iPmrver = value; }
        }

        public string ISpname
        {
            get { return iSpname; }
            set { iSpname = value; }
        }

        public System.DateTime ISpdate
        {
            get { return iSpdate; }
            set { iSpdate = value; }
        }

        public string IStatus
        {
            get { return iStatus; }
            set { iStatus = value; }
        }

        public string ISephin
        {
            get { return iSephin; }
            set { iSephin = value; }
        }

        public string IRyuhin
        {
            get { return iRyuhin; }
            set { iRyuhin = value; }
        }

        public string ISakusei
        {
            get { return iSakusei; }
            set { iSakusei = value; }
        }

        public string ICtrlSection
        {
            get { return iCtrlSection; }
            set { iCtrlSection = value; }
        }

        public string ISalesSection
        {
            get { return iSalesSection; }
            set { iSalesSection = value; }
        }

        public string IPurchaseSection
        {
            get { return iPurchaseSection; }
            set { iPurchaseSection = value; }
        }

        public string IItemEntryCls
        {
            get { return iItemEntryCls; }
            set { iItemEntryCls = value; }
        }

        public string ISmtCls
        {
            get { return iSmtCls; }
            set { iSmtCls = value; }
        }

        public string IRohsCls
        {
            get { return iRohsCls; }
            set { iRohsCls = value; }
        }

        public string IReachCls
        {
            get { return iReachCls; }
            set { iReachCls = value; }
        }

        public string IChinaRohsCls
        {
            get { return iChinaRohsCls; }
            set { iChinaRohsCls = value; }
        }

        public decimal IBinEndDate
        {
            get { return iBinEndDate; }
            set { iBinEndDate = value; }
        }

        public string IMntCls
        {
            get { return iMntCls; }
            set { iMntCls = value; }
        }

        public string ISrlSeqCls
        {
            get { return iSrlSeqCls; }
            set { iSrlSeqCls = value; }
        }

        public decimal IPartChgPeriod
        {
            get { return iPartChgPeriod; }
            set { iPartChgPeriod = value; }
        }

        public string IPartChgPeriodUnitCd
        {
            get { return iPartChgPeriodUnitCd; }
            set { iPartChgPeriodUnitCd = value; }
        }

        public decimal IFixMntPeriod
        {
            get { return iFixMntPeriod; }
            set { iFixMntPeriod = value; }
        }

        public string IFixMntPeriodUnitCd
        {
            get { return iFixMntPeriodUnitCd; }
            set { iFixMntPeriodUnitCd = value; }
        }

        public decimal IGuarPeriod
        {
            get { return iGuarPeriod; }
            set { iGuarPeriod = value; }
        }

        public string IGuarPeriodUnitCd
        {
            get { return iGuarPeriodUnitCd; }
            set { iGuarPeriodUnitCd = value; }
        }

        public decimal IUsefulLife
        {
            get { return iUsefulLife; }
            set { iUsefulLife = value; }
        }

        public string IUsefulLifeUnitCls
        {
            get { return iUsefulLifeUnitCls; }
            set { iUsefulLifeUnitCls = value; }
        }

        public string ICapItemType
        {
            get { return iCapItemType; }
            set { iCapItemType = value; }
        }

        public string IInqItem
        {
            get { return iInqItem; }
            set { iInqItem = value; }
        }

        public decimal IObjectId
        {
            get { return iObjectId; }
            set { iObjectId = value; }
        }

        public string IDlCd
        {
            get { return iDlCd; }
            set { iDlCd = value; }
        }

        public string IHinsyosai1
        {
            get { return iHinsyosai1; }
            set { iHinsyosai1 = value; }
        }

        public string IHinsyosai2
        {
            get { return iHinsyosai2; }
            set { iHinsyosai2 = value; }
        }

        public string IHinsyosai3
        {
            get { return iHinsyosai3; }
            set { iHinsyosai3 = value; }
        }

        public string IHinsyosai4
        {
            get { return iHinsyosai4; }
            set { iHinsyosai4 = value; }
        }

        public string IHinsyosai5
        {
            get { return iHinsyosai5; }
            set { iHinsyosai5 = value; }
        }

        public string IHkhinno1
        {
            get { return iHkhinno1; }
            set { iHkhinno1 = value; }
        }

        public string IHkhinno2
        {
            get { return iHkhinno2; }
            set { iHkhinno2 = value; }
        }

        public string IHkhinno3
        {
            get { return iHkhinno3; }
            set { iHkhinno3 = value; }
        }

        public string IHinzks1
        {
            get { return iHinzks1; }
            set { iHinzks1 = value; }
        }

        public string IHinzks2
        {
            get { return iHinzks2; }
            set { iHinzks2 = value; }
        }

        public string IHinzks3
        {
            get { return iHinzks3; }
            set { iHinzks3 = value; }
        }

        public string IZryobnr
        {
            get { return iZryobnr; }
            set { iZryobnr = value; }
        }

        public string ICsthskkbn
        {
            get { return iCsthskkbn; }
            set { iCsthskkbn = value; }
        }

        public string ICstkskbn
        {
            get { return iCstkskbn; }
            set { iCstkskbn = value; }
        }

        public string IKgsankbn
        {
            get { return iKgsankbn; }
            set { iKgsankbn = value; }
        }

        public string ISkrkejkbn
        {
            get { return iSkrkejkbn; }
            set { iSkrkejkbn = value; }
        }

        public string ITmhskkbn
        {
            get { return iTmhskkbn; }
            set { iTmhskkbn = value; }
        }

        public string ITmzryobnr
        {
            get { return iTmzryobnr; }
            set { iTmzryobnr = value; }
        }

        public decimal ITmcstmkno
        {
            get { return iTmcstmkno; }
            set { iTmcstmkno = value; }
        }

        public string ISzcrtkbn
        {
            get { return iSzcrtkbn; }
            set { iSzcrtkbn = value; }
        }

        public decimal IHdtkzchBnshi
        {
            get { return iHdtkzchBnshi; }
            set { iHdtkzchBnshi = value; }
        }

        public decimal IHdtkzchBnbo
        {
            get { return iHdtkzchBnbo; }
            set { iHdtkzchBnbo = value; }
        }

        public string IHdkmtnicd
        {
            get { return iHdkmtnicd; }
            set { iHdkmtnicd = value; }
        }

        public decimal ILotSesanryo
        {
            get { return iLotSesanryo; }
            set { iLotSesanryo = value; }
        }

        public decimal IDaySesanryo
        {
            get { return iDaySesanryo; }
            set { iDaySesanryo = value; }
        }

        public decimal IYieldRate
        {
            get { return iYieldRate; }
            set { iYieldRate = value; }
        }

        public string IFukukbn
        {
            get { return iFukukbn; }
            set { iFukukbn = value; }
        }

        public string ISgenkbn
        {
            get { return iSgenkbn; }
            set { iSgenkbn = value; }
        }

        public string ITenfuykbn
        {
            get { return iTenfuykbn; }
            set { iTenfuykbn = value; }
        }

        public string IDaikoteptn
        {
            get { return iDaikoteptn; }
            set { iDaikoteptn = value; }
        }

        public string IDhhigptn
        {
            get { return iDhhigptn; }
            set { iDhhigptn = value; }
        }

        public decimal IZktkzchBnshi1
        {
            get { return iZktkzchBnshi1; }
            set { iZktkzchBnshi1 = value; }
        }

        public decimal IZktkzchBnbo1
        {
            get { return iZktkzchBnbo1; }
            set { iZktkzchBnbo1 = value; }
        }

        public string IZktikzticd1
        {
            get { return iZktikzticd1; }
            set { iZktikzticd1 = value; }
        }

        public decimal IZktkzchBnshi2
        {
            get { return iZktkzchBnshi2; }
            set { iZktkzchBnshi2 = value; }
        }

        public decimal IZktkzchBnbo2
        {
            get { return iZktkzchBnbo2; }
            set { iZktkzchBnbo2 = value; }
        }

        public string IZktikzticd2
        {
            get { return iZktikzticd2; }
            set { iZktikzticd2 = value; }
        }

        public decimal IZktkzchBnshi3
        {
            get { return iZktkzchBnshi3; }
            set { iZktkzchBnshi3 = value; }
        }

        public decimal IZktkzchBnbo3
        {
            get { return iZktkzchBnbo3; }
            set { iZktkzchBnbo3 = value; }
        }

        public string IZktikzticd3
        {
            get { return iZktikzticd3; }
            set { iZktikzticd3 = value; }
        }

        public decimal IZktkzchBnshi4
        {
            get { return iZktkzchBnshi4; }
            set { iZktkzchBnshi4 = value; }
        }

        public decimal IZktkzchBnbo4
        {
            get { return iZktkzchBnbo4; }
            set { iZktkzchBnbo4 = value; }
        }

        public string IZktikzticd4
        {
            get { return iZktikzticd4; }
            set { iZktikzticd4 = value; }
        }

        public decimal IZktkzchBnshi5
        {
            get { return iZktkzchBnshi5; }
            set { iZktkzchBnshi5 = value; }
        }

        public decimal IZktkzchBnbo5
        {
            get { return iZktkzchBnbo5; }
            set { iZktkzchBnbo5 = value; }
        }

        public string IZktikzticd5
        {
            get { return iZktikzticd5; }
            set { iZktikzticd5 = value; }
        }

        public decimal IHinksu01
        {
            get { return iHinksu01; }
            set { iHinksu01 = value; }
        }

        public decimal IHinksu02
        {
            get { return iHinksu02; }
            set { iHinksu02 = value; }
        }

        public decimal IHinksu03
        {
            get { return iHinksu03; }
            set { iHinksu03 = value; }
        }

        public decimal IHinksu04
        {
            get { return iHinksu04; }
            set { iHinksu04 = value; }
        }

        public decimal IHinksu05
        {
            get { return iHinksu05; }
            set { iHinksu05 = value; }
        }

        public decimal IHinksu06
        {
            get { return iHinksu06; }
            set { iHinksu06 = value; }
        }

        public decimal IHinksu07
        {
            get { return iHinksu07; }
            set { iHinksu07 = value; }
        }

        public decimal IHinksu08
        {
            get { return iHinksu08; }
            set { iHinksu08 = value; }
        }

        public decimal IHinksu09
        {
            get { return iHinksu09; }
            set { iHinksu09 = value; }
        }

        public decimal IHinksu10
        {
            get { return iHinksu10; }
            set { iHinksu10 = value; }
        }

        public string IHinbnr01
        {
            get { return iHinbnr01; }
            set { iHinbnr01 = value; }
        }

        public string IHinbnr02
        {
            get { return iHinbnr02; }
            set { iHinbnr02 = value; }
        }

        public string IHinbnr03
        {
            get { return iHinbnr03; }
            set { iHinbnr03 = value; }
        }

        public string IHinbnr04
        {
            get { return iHinbnr04; }
            set { iHinbnr04 = value; }
        }

        public string IHinbnr05
        {
            get { return iHinbnr05; }
            set { iHinbnr05 = value; }
        }

        public string IHinbnr06
        {
            get { return iHinbnr06; }
            set { iHinbnr06 = value; }
        }

        public string IHinbnr07
        {
            get { return iHinbnr07; }
            set { iHinbnr07 = value; }
        }

        public string IHinbnr08
        {
            get { return iHinbnr08; }
            set { iHinbnr08 = value; }
        }

        public string IHinbnr09
        {
            get { return iHinbnr09; }
            set { iHinbnr09 = value; }
        }

        public string IHinbnr10
        {
            get { return iHinbnr10; }
            set { iHinbnr10 = value; }
        }

        public string IJohhtkbn
        {
            get { return iJohhtkbn; }
            set { iJohhtkbn = value; }
        }

        public string IHftkbn1
        {
            get { return iHftkbn1; }
            set { iHftkbn1 = value; }
        }

        public string IHftkbn2
        {
            get { return iHftkbn2; }
            set { iHftkbn2 = value; }
        }

        public string IHftkbn3
        {
            get { return iHftkbn3; }
            set { iHftkbn3 = value; }
        }

        public string IHftkbn4
        {
            get { return iHftkbn4; }
            set { iHftkbn4 = value; }
        }

        public string IHftkbn5
        {
            get { return iHftkbn5; }
            set { iHftkbn5 = value; }
        }

        public string ISytsukakbn
        {
            get { return iSytsukakbn; }
            set { iSytsukakbn = value; }
        }

        public string ITngmhfkbn
        {
            get { return iTngmhfkbn; }
            set { iTngmhfkbn = value; }
        }

        public string ITnhkshfkbn
        {
            get { return iTnhkshfkbn; }
            set { iTnhkshfkbn = value; }
        }

        public string VItemclsdesc
        {
            get { return vItemclsdesc; }
            set { vItemclsdesc = value; }
        }

        public string VCtrlclsdesc
        {
            get { return vCtrlclsdesc; }
            set { vCtrlclsdesc = value; }
        }

        public string VLotctrlclsdesc
        {
            get { return vLotctrlclsdesc; }
            set { vLotctrlclsdesc = value; }
        }

        public string VUsedelclsdesc
        {
            get { return vUsedelclsdesc; }
            set { vUsedelclsdesc = value; }
        }

        public string VSoalcclsdesc
        {
            get { return vSoalcclsdesc; }
            set { vSoalcclsdesc = value; }
        }

        public string VPsclsdesc
        {
            get { return vPsclsdesc; }
            set { vPsclsdesc = value; }
        }

        public string VSmtclsdesc
        {
            get { return vSmtclsdesc; }
            set { vSmtclsdesc = value; }
        }

        public string VRohsclsdesc
        {
            get { return vRohsclsdesc; }
            set { vRohsclsdesc = value; }
        }

        public string VReachclsdesc
        {
            get { return vReachclsdesc; }
            set { vReachclsdesc = value; }
        }

        public string VChinarohsclsdesc
        {
            get { return vChinarohsclsdesc; }
            set { vChinarohsclsdesc = value; }
        }

        public string VOsalcclsdesc
        {
            get { return vOsalcclsdesc; }
            set { vOsalcclsdesc = value; }
        }

        public string VCsthskkbndesc
        {
            get { return vCsthskkbndesc; }
            set { vCsthskkbndesc = value; }
        }

        public string VCstkskbndesc
        {
            get { return vCstkskbndesc; }
            set { vCstkskbndesc = value; }
        }

        public string VKgsankbndesc
        {
            get { return vKgsankbndesc; }
            set { vKgsankbndesc = value; }
        }

        public string VSkrkejkbndesc
        {
            get { return vSkrkejkbndesc; }
            set { vSkrkejkbndesc = value; }
        }

        public string VTmhskkbndesc
        {
            get { return vTmhskkbndesc; }
            set { vTmhskkbndesc = value; }
        }

        public string VSzcrtkbndesc
        {
            get { return vSzcrtkbndesc; }
            set { vSzcrtkbndesc = value; }
        }

        public string VFukukbndesc
        {
            get { return vFukukbndesc; }
            set { vFukukbndesc = value; }
        }

        public string VSgenkbndesc
        {
            get { return vSgenkbndesc; }
            set { vSgenkbndesc = value; }
        }

        public string VTenfuykbndesc
        {
            get { return vTenfuykbndesc; }
            set { vTenfuykbndesc = value; }
        }

        public string VJohhtkbndesc
        {
            get { return vJohhtkbndesc; }
            set { vJohhtkbndesc = value; }
        }

        public string VHftkbndesc1
        {
            get { return vHftkbndesc1; }
            set { vHftkbndesc1 = value; }
        }

        public string VHftkbndesc2
        {
            get { return vHftkbndesc2; }
            set { vHftkbndesc2 = value; }
        }

        public string VHftkbndesc3
        {
            get { return vHftkbndesc3; }
            set { vHftkbndesc3 = value; }
        }

        public string VHftkbndesc4
        {
            get { return vHftkbndesc4; }
            set { vHftkbndesc4 = value; }
        }

        public string VHftkbndesc5
        {
            get { return vHftkbndesc5; }
            set { vHftkbndesc5 = value; }
        }

        public string VItemtypedesc
        {
            get { return vItemtypedesc; }
            set { vItemtypedesc = value; }
        }

        public string VItemtype1desc
        {
            get { return vItemtype1desc; }
            set { vItemtype1desc = value; }
        }


        public string VItemtype3desc
        {
            get { return vItemtype3desc; }
            set { vItemtype3desc = value; }
        }

        public string VMakerdesc
        {
            get { return vMakerdesc; }
            set { vMakerdesc = value; }
        }

        public string VZryobnrdesc
        {
            get { return vZryobnrdesc; }
            set { vZryobnrdesc = value; }
        }

        public string VTmzryobnrdesc
        {
            get { return vTmzryobnrdesc; }
            set { vTmzryobnrdesc = value; }
        }

        public string VHinbnr01desc
        {
            get { return vHinbnr01desc; }
            set { vHinbnr01desc = value; }
        }

        public string VHinbnr02desc
        {
            get { return vHinbnr02desc; }
            set { vHinbnr02desc = value; }
        }

        public string VHinbnr03desc
        {
            get { return vHinbnr03desc; }
            set { vHinbnr03desc = value; }
        }

        public string VHinbnr04desc
        {
            get { return vHinbnr04desc; }
            set { vHinbnr04desc = value; }
        }

        public string VHinbnr05desc
        {
            get { return vHinbnr05desc; }
            set { vHinbnr05desc = value; }
        }

        public string VHinbnr06desc
        {
            get { return vHinbnr06desc; }
            set { vHinbnr06desc = value; }
        }

        public string VHinbnr07desc
        {
            get { return vHinbnr07desc; }
            set { vHinbnr07desc = value; }
        }

        public string VHinbnr08desc
        {
            get { return vHinbnr08desc; }
            set { vHinbnr08desc = value; }
        }

        public string VHinbnr09desc
        {
            get { return vHinbnr09desc; }
            set { vHinbnr09desc = value; }
        }

        public string VHinbnr10desc
        {
            get { return vHinbnr10desc; }
            set { vHinbnr10desc = value; }
        }

        public string VHdkmtnicddesc
        {
            get { return vHdkmtnicddesc; }
            set { vHdkmtnicddesc = value; }
        }

        public string VZktikzticd1desc
        {
            get { return vZktikzticd1desc; }
            set { vZktikzticd1desc = value; }
        }

        public string VZktikzticd2desc
        {
            get { return vZktikzticd2desc; }
            set { vZktikzticd2desc = value; }
        }

        public string VZktikzticd3desc
        {
            get { return vZktikzticd3desc; }
            set { vZktikzticd3desc = value; }
        }

        public string VZktikzticd4desc
        {
            get { return vZktikzticd4desc; }
            set { vZktikzticd4desc = value; }
        }

        public string VZktikzticd5desc
        {
            get { return vZktikzticd5desc; }
            set { vZktikzticd5desc = value; }
        }

        public string VCtrlsectiondesc
        {
            get { return vCtrlsectiondesc; }
            set { vCtrlsectiondesc = value; }
        }

        public string VStocklocationdesc
        {
            get { return vStocklocationdesc; }
            set { vStocklocationdesc = value; }
        }

        public string VFacdesc
        {
            get { return vFacdesc; }
            set { vFacdesc = value; }
        }

        public string VPersondesc
        {
            get { return vPersondesc; }
            set { vPersondesc = value; }
        }

        public string IStdunitdesc
        {
            get { return iStdunitdesc; }
            set { iStdunitdesc = value; }
        }

        public string ICnvunitdesc
        {
            get { return iCnvunitdesc; }
            set { iCnvunitdesc = value; }
        }

        public string INetweightunitdesc
        {
            get { return iNetweightunitdesc; }
            set { iNetweightunitdesc = value; }
        }

        public string IPartchgperiodunitdesc
        {
            get { return iPartchgperiodunitdesc; }
            set { iPartchgperiodunitdesc = value; }
        }

        public string IFixmntperiodunitdesc
        {
            get { return iFixmntperiodunitdesc; }
            set { iFixmntperiodunitdesc = value; }
        }

        public string IGuarperiodunitdesc
        {
            get { return iGuarperiodunitdesc; }
            set { iGuarperiodunitdesc = value; }
        }

        public string IMntclsdesc
        {
            get { return iMntclsdesc; }
            set { iMntclsdesc = value; }
        }

        public string ISrlseqclsdesc
        {
            get { return iSrlseqclsdesc; }
            set { iSrlseqclsdesc = value; }
        }

        public string IUsefullifeunitclsdesc
        {
            get { return iUsefullifeunitclsdesc; }
            set { iUsefullifeunitclsdesc = value; }
        }



        public string VDlDesc
        {
            get { return vDlDesc; }
            set { vDlDesc = value; }
        }



        public System.DateTime IEntryDate
        {
            get { return iEntryDate; }
            set { iEntryDate = value; }
        }

        public System.DateTime IUpdDate
        {
            get { return iUpdDate; }
            set { iUpdDate = value; }
        }

        public string IUpdTimestamp
        {
            get { return iUpdTimestamp; }
            set { iUpdTimestamp = value; }
        }
    }
}
