using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using Castle.ActiveRecord;
using Castle.ActiveRecord.Queries;


#region 'M_FUNCTION' Schema
/*
 * 'MFunction' class maps to 'M_FUNCTION' table.
 * 	 LANGID                  | Type:NVARCHAR2 | Len:10    | Nullable:F | PK:T | FK:F
 * 	 FUNCTIONID              | Type:NUMBER    | Len:0     | Nullable:F | PK:T | FK:F
 * 	 FUNCTIONNAME            | Type:NVARCHAR2 | Len:100   | Nullable:T | PK:F | FK:F
 * 	 FUNCTIONPATH            | Type:NVARCHAR2 | Len:100   | Nullable:T | PK:F | FK:F
 * 	 CATALOGID               | Type:NUMBER    | Len:0     | Nullable:F | PK:F | FK:F
 */
#endregion
/// <summary>
///	Generated by MyGeneration using the ActiveRecord Object Mapper - 1.0.2
///	
/// 
///	Created on 2011/8/24 20:15:02
/// </summary>
namespace Com.GainWinSoft.ERP.Entity
{
    [Serializable]
    public class CCatalogFunctionNoAR 
    {

		#region Private Members

        private string langid;
        public string Langid
        {
            get { return langid; }
            set { langid = value; }
        }
        private int functionid;

        public int Functionid
        {
            get { return functionid; }
            set { functionid = value; }
        }

        private string functionname;
        public string Functionname
        {
            get { return functionname; }
            set { functionname = value; }
        }
        private string functionpath;

        public string Functionpath
        {
            get { return functionpath; }
            set { functionpath = value; }
        }
        private int catalogid;

        public int Catalogid
        {
            get { return catalogid; }
            set { catalogid = value; }
        }
        private int functionindex;

        public int Functionindex
        {
            get { return functionindex; }
            set { functionindex = value; }
        }
        private string functionimage;

        public string Functionimage
        {
            get { return functionimage; }
            set { functionimage = value; }
        }

        private string catalogname;

        public string Catalogname
        {
            get { return catalogname; }
            set { catalogname = value; }
        }
        private string catalogimage;

        public string Catalogimage
        {
            get { return catalogimage; }
            set { catalogimage = value; }
        }

		#endregion

	}
}
