//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3623
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.GainWinSoft.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.GainWinSoft.Common.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   系统异常，请和系统管理员联系。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0001 {
            get {
                return ResourceManager.GetString("E0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   请先关闭【%1】子窗口。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0002 {
            get {
                return ResourceManager.GetString("E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加载初始数据…… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0001 {
            get {
                return ResourceManager.GetString("I0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加载菜单项…… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0002 {
            get {
                return ResourceManager.GetString("I0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加载主画面…… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0003 {
            get {
                return ResourceManager.GetString("I0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加载用户数据…… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0004 {
            get {
                return ResourceManager.GetString("I0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   维护系统运行中使用的基础数据的最基本模块，是基本数据输入的入口。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0101 {
            get {
                return ResourceManager.GetString("I0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   客户报价单和订单的输入和查询，主要功能是通过统一订单提供用户整合的一站式供应链服务，订单管理以及订单跟踪管理能够使用户的物流服务得到全程的满足。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0102 {
            get {
                return ResourceManager.GetString("I0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数据库操作失败，错误代码：%1  错误内容：%2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S0001 {
            get {
                return ResourceManager.GetString("S0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 不能为空，请输入。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string W0001 {
            get {
                return ResourceManager.GetString("W0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 的格式不正确 %2。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string W0002 {
            get {
                return ResourceManager.GetString("W0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   用户代码或者密码不正确。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string W0003 {
            get {
                return ResourceManager.GetString("W0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 在数据表中不存在，请重新输入。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string W0004 {
            get {
                return ResourceManager.GetString("W0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   没有查询到符合条件的数据。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string W0005 {
            get {
                return ResourceManager.GetString("W0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   请选择一条数据 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string W0006 {
            get {
                return ResourceManager.GetString("W0006", resourceCulture);
            }
        }
    }
}
