//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5446
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.GainWinSoft.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.GainWinSoft.Common.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 系统异常，请和系统管理员联系。 的本地化字符串。
        /// </summary>
        internal static string E0001 {
            get {
                return ResourceManager.GetString("E0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先关闭【%1】子窗口。 的本地化字符串。
        /// </summary>
        internal static string E0002 {
            get {
                return ResourceManager.GetString("E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载初始数据…… 的本地化字符串。
        /// </summary>
        internal static string I0001 {
            get {
                return ResourceManager.GetString("I0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载菜单项…… 的本地化字符串。
        /// </summary>
        internal static string I0002 {
            get {
                return ResourceManager.GetString("I0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载主画面…… 的本地化字符串。
        /// </summary>
        internal static string I0003 {
            get {
                return ResourceManager.GetString("I0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载用户数据…… 的本地化字符串。
        /// </summary>
        internal static string I0004 {
            get {
                return ResourceManager.GetString("I0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维护系统运行中使用的基础数据的最基本模块，是基本数据输入的入口。 的本地化字符串。
        /// </summary>
        internal static string I0101 {
            get {
                return ResourceManager.GetString("I0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户报价单和订单的输入和查询，主要功能是通过统一订单提供用户整合的一站式供应链服务，订单管理以及订单跟踪管理能够使用户的物流服务得到全程的满足。 的本地化字符串。
        /// </summary>
        internal static string I0102 {
            get {
                return ResourceManager.GetString("I0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库操作失败，错误代码：%1  错误内容：%2 的本地化字符串。
        /// </summary>
        internal static string S0001 {
            get {
                return ResourceManager.GetString("S0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %1 不能为空，请输入。 的本地化字符串。
        /// </summary>
        internal static string W0001 {
            get {
                return ResourceManager.GetString("W0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %1 的格式不正确 %2。 的本地化字符串。
        /// </summary>
        internal static string W0002 {
            get {
                return ResourceManager.GetString("W0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户代码或者密码不正确。 的本地化字符串。
        /// </summary>
        internal static string W0003 {
            get {
                return ResourceManager.GetString("W0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %1 在数据表中不存在，请重新输入。 的本地化字符串。
        /// </summary>
        internal static string W0004 {
            get {
                return ResourceManager.GetString("W0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有查询到符合条件的数据。 的本地化字符串。
        /// </summary>
        internal static string W0005 {
            get {
                return ResourceManager.GetString("W0005", resourceCulture);
            }
        }
    }
}
