//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5446
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.GainWinSoft.ERP.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.GainWinSoft.ERP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AccountItem {
            get {
                object obj = ResourceManager.GetObject("AccountItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AchievementBudgetEntry {
            get {
                object obj = ResourceManager.GetObject("AchievementBudgetEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bom {
            get {
                object obj = ResourceManager.GetObject("Bom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calendar {
            get {
                object obj = ResourceManager.GetObject("Calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CompanyData {
            get {
                object obj = ResourceManager.GetObject("CompanyData", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Composition {
            get {
                object obj = ResourceManager.GetObject("Composition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CompositionCheck {
            get {
                object obj = ResourceManager.GetObject("CompositionCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cost16 {
            get {
                object obj = ResourceManager.GetObject("Cost16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cost24 {
            get {
                object obj = ResourceManager.GetObject("Cost24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cost48 {
            get {
                object obj = ResourceManager.GetObject("Cost48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Currency {
            get {
                object obj = ResourceManager.GetObject("Currency", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Customer {
            get {
                object obj = ResourceManager.GetObject("Customer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CustomerMaterial {
            get {
                object obj = ResourceManager.GetObject("CustomerMaterial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DefaultProgram {
            get {
                object obj = ResourceManager.GetObject("DefaultProgram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeliveryEntry {
            get {
                object obj = ResourceManager.GetObject("DeliveryEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeliveryReceiptPrint {
            get {
                object obj = ResourceManager.GetObject("DeliveryReceiptPrint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeliveryResultInquiry {
            get {
                object obj = ResourceManager.GetObject("DeliveryResultInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DemandCompute {
            get {
                object obj = ResourceManager.GetObject("DemandCompute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Department {
            get {
                object obj = ResourceManager.GetObject("Department", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EstimateInventoryInquiry {
            get {
                object obj = ResourceManager.GetObject("EstimateInventoryInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExchangeRate {
            get {
                object obj = ResourceManager.GetObject("ExchangeRate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Factory {
            get {
                object obj = ResourceManager.GetObject("Factory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory16 {
            get {
                object obj = ResourceManager.GetObject("Inventory16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory24 {
            get {
                object obj = ResourceManager.GetObject("Inventory24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory48 {
            get {
                object obj = ResourceManager.GetObject("Inventory48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventoryAdjustmentEntry {
            get {
                object obj = ResourceManager.GetObject("InventoryAdjustmentEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventoryAssetsReprot {
            get {
                object obj = ResourceManager.GetObject("InventoryAssetsReprot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventoryCheckEntry {
            get {
                object obj = ResourceManager.GetObject("InventoryCheckEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventoryCheckSetting {
            get {
                object obj = ResourceManager.GetObject("InventoryCheckSetting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventoryDifferenceReport {
            get {
                object obj = ResourceManager.GetObject("InventoryDifferenceReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventoryExcessReport {
            get {
                object obj = ResourceManager.GetObject("InventoryExcessReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventoryInformation {
            get {
                object obj = ResourceManager.GetObject("InventoryInformation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventoryInstructionReport {
            get {
                object obj = ResourceManager.GetObject("InventoryInstructionReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventoryMonthlyCarryOver {
            get {
                object obj = ResourceManager.GetObject("InventoryMonthlyCarryOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventoryMove {
            get {
                object obj = ResourceManager.GetObject("InventoryMove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventoryUpdate {
            get {
                object obj = ResourceManager.GetObject("InventoryUpdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap leftdown {
            get {
                object obj = ResourceManager.GetObject("leftdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap leftup {
            get {
                object obj = ResourceManager.GetObject("leftup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loginbg {
            get {
                object obj = ResourceManager.GetObject("loginbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LotTraceInquiry {
            get {
                object obj = ResourceManager.GetObject("LotTraceInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureBatchCostInquiry {
            get {
                object obj = ResourceManager.GetObject("ManufactureBatchCostInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureBatchEntry {
            get {
                object obj = ResourceManager.GetObject("ManufactureBatchEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureBatchInstructionEntry {
            get {
                object obj = ResourceManager.GetObject("ManufactureBatchInstructionEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureBatchInstructionInquiry {
            get {
                object obj = ResourceManager.GetObject("ManufactureBatchInstructionInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureBatchProcessAlertInquiry {
            get {
                object obj = ResourceManager.GetObject("ManufactureBatchProcessAlertInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureInstructionEntry {
            get {
                object obj = ResourceManager.GetObject("ManufactureInstructionEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureInstructionExecute {
            get {
                object obj = ResourceManager.GetObject("ManufactureInstructionExecute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureInstructionPickingEntry {
            get {
                object obj = ResourceManager.GetObject("ManufactureInstructionPickingEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureInstructionRemainInquiry {
            get {
                object obj = ResourceManager.GetObject("ManufactureInstructionRemainInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureManagement16 {
            get {
                object obj = ResourceManager.GetObject("ManufactureManagement16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureManagement24 {
            get {
                object obj = ResourceManager.GetObject("ManufactureManagement24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureManagement48 {
            get {
                object obj = ResourceManager.GetObject("ManufactureManagement48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureOrder {
            get {
                object obj = ResourceManager.GetObject("ManufactureOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufacturePlan16 {
            get {
                object obj = ResourceManager.GetObject("ManufacturePlan16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufacturePlan24 {
            get {
                object obj = ResourceManager.GetObject("ManufacturePlan24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufacturePlan48 {
            get {
                object obj = ResourceManager.GetObject("ManufacturePlan48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufacturePlanEntry {
            get {
                object obj = ResourceManager.GetObject("ManufacturePlanEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufacturePlanInquiry {
            get {
                object obj = ResourceManager.GetObject("ManufacturePlanInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManufactureResultEntry {
            get {
                object obj = ResourceManager.GetObject("ManufactureResultEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MasterData16 {
            get {
                object obj = ResourceManager.GetObject("MasterData16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MasterData24 {
            get {
                object obj = ResourceManager.GetObject("MasterData24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MasterData48 {
            get {
                object obj = ResourceManager.GetObject("MasterData48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Material {
            get {
                object obj = ResourceManager.GetObject("Material", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MaterialInventoryInquiry {
            get {
                object obj = ResourceManager.GetObject("MaterialInventoryInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MaterialPrice {
            get {
                object obj = ResourceManager.GetObject("MaterialPrice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OrderEntry {
            get {
                object obj = ResourceManager.GetObject("OrderEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OrderInquiry {
            get {
                object obj = ResourceManager.GetObject("OrderInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PickingDetails {
            get {
                object obj = ResourceManager.GetObject("PickingDetails", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PickingEstimatePickingList {
            get {
                object obj = ResourceManager.GetObject("PickingEstimatePickingList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessEquipment {
            get {
                object obj = ResourceManager.GetObject("ProcessEquipment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProspectDemandCompute {
            get {
                object obj = ResourceManager.GetObject("ProspectDemandCompute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProspectManufacturePlanEntry {
            get {
                object obj = ResourceManager.GetObject("ProspectManufacturePlanEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purchase16 {
            get {
                object obj = ResourceManager.GetObject("Purchase16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purchase24 {
            get {
                object obj = ResourceManager.GetObject("Purchase24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purchase48 {
            get {
                object obj = ResourceManager.GetObject("Purchase48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurchaseOrder {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurchaseReplenishmentInquiry {
            get {
                object obj = ResourceManager.GetObject("PurchaseReplenishmentInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quotation16 {
            get {
                object obj = ResourceManager.GetObject("Quotation16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quotation24 {
            get {
                object obj = ResourceManager.GetObject("Quotation24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quotation48 {
            get {
                object obj = ResourceManager.GetObject("Quotation48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QuotationEntry {
            get {
                object obj = ResourceManager.GetObject("QuotationEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QuotationInquiry {
            get {
                object obj = ResourceManager.GetObject("QuotationInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReceiptEntry {
            get {
                object obj = ResourceManager.GetObject("ReceiptEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReceiptPickingInquiry {
            get {
                object obj = ResourceManager.GetObject("ReceiptPickingInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReceiptQualityInspectionEntry {
            get {
                object obj = ResourceManager.GetObject("ReceiptQualityInspectionEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReceiptQualityInspectionReport {
            get {
                object obj = ResourceManager.GetObject("ReceiptQualityInspectionReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReceiptResultInquiry {
            get {
                object obj = ResourceManager.GetObject("ReceiptResultInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportCenter16 {
            get {
                object obj = ResourceManager.GetObject("ReportCenter16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportCenter24 {
            get {
                object obj = ResourceManager.GetObject("ReportCenter24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReportCenter48 {
            get {
                object obj = ResourceManager.GetObject("ReportCenter48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReturnEntry {
            get {
                object obj = ResourceManager.GetObject("ReturnEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rightdown {
            get {
                object obj = ResourceManager.GetObject("rightdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rightup {
            get {
                object obj = ResourceManager.GetObject("rightup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Role {
            get {
                object obj = ResourceManager.GetObject("Role", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SalesDelivery16 {
            get {
                object obj = ResourceManager.GetObject("SalesDelivery16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SalesDelivery24 {
            get {
                object obj = ResourceManager.GetObject("SalesDelivery24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SalesDelivery48 {
            get {
                object obj = ResourceManager.GetObject("SalesDelivery48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SalesResultEntry {
            get {
                object obj = ResourceManager.GetObject("SalesResultEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splash {
            get {
                object obj = ResourceManager.GetObject("splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SystemParameter {
            get {
                object obj = ResourceManager.GetObject("SystemParameter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnplanedReceiptEntry {
            get {
                object obj = ResourceManager.GetObject("UnplanedReceiptEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User {
            get {
                object obj = ResourceManager.GetObject("User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WarehouseProcess {
            get {
                object obj = ResourceManager.GetObject("WarehouseProcess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorkProcess16 {
            get {
                object obj = ResourceManager.GetObject("WorkProcess16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorkProcess24 {
            get {
                object obj = ResourceManager.GetObject("WorkProcess24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorkProcess48 {
            get {
                object obj = ResourceManager.GetObject("WorkProcess48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorkSheetEntry {
            get {
                object obj = ResourceManager.GetObject("WorkSheetEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorkSheetInquiry {
            get {
                object obj = ResourceManager.GetObject("WorkSheetInquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
